In [16]:
import pandas as pd

In [17]:
df = pd.read_csv("answers.csv")
df

,Unnamed: 0,query,занятость,по должности-лемме,по дополнительному признаку,по условиям,общие фразы
0,0,фарпост работа владивосток,NaN,NaN,NaN,NaN,общая фраза
1,1,кофейни вакансии,NaN,NaN,NaN,NaN,общая фраза
2,2,работа разнорабочие часовой,NaN,Рабочий,NaN,NaN,NaN
3,3,личный водитель на день,на неполный день,Водитель,NaN,NaN,NaN
4,4,работа от работодателя персональный водитель,NaN,Водитель,NaN,NaN,NaN
...,...,...,...,...,...,...,...
14240,14240,япония вакансии,NaN,NaN,NaN,NaN,общая фраза
14241,14241,япония работа,NaN,NaN,NaN,NaN,общая фраза
14242,14242,японский язык работа,NaN,NaN,NaN,NaN,общая фраза
14243,14243,яппи вакансии,NaN,NaN,NaN,NaN,общая фраза
14244,14244,ёбидоёби вакансии,NaN,NaN,NaN,NaN,общая фраза

In [18]:
df = df[['query', 'по должности-лемме']]

In [19]:
df = df[df['по должности-лемме'].notna()]

In [20]:
df

                                              query по должности-лемме
2                       работа разнорабочие часовой            Рабочий
3                           личный водитель на день           Водитель
4      работа от работодателя персональный водитель           Водитель
8                  скачать приложение курьер работа             Курьер
9                      работа финансовым директором           Директор
...                                             ...                ...
14234                 яндекс курьер без термокороба             Курьер
14235                        яндекс курьер доставка             Курьер
14236                         яндекс курьер на авто             Курьер
14237                     яндекс логистика вакансии             Логист
14238                       яндекс про курьер пеший             Курьер

[7883 rows x 2 columns]

In [22]:
df['по должности-лемме'].unique()

array(['Рабочий', 'Водитель', 'Курьер', 'Директор', 'Менеджер',
       'Ассистент', 'Помощник', 'Химик', 'Медсестра, медбрат',
       'Руководитель, начальник', 'Уборщик, горничная', 'Специалист АХО',
       'Вахтер', 'Механик', 'Комплектовщик', 'Инженер', 'Оценщик',
       'Грузчик', 'Кладовщик', 'Сварщик', 'Фасовщик', 'Модератор',
       'Продавец', 'Юрист', 'Парковщик', 'Кухонный работник', 'Формовщик',
       'Мясник', 'Администратор', 'Юрисконсульт', 'Инспектор',
       'Бортпроводник', 'Вожатый', 'Математик', 'Матрос', 'Машинист',
       'Инкассатор', 'Капитан', 'Косметолог', 'Лифтер', 'Механизатор',
       'Заправщик АЗС', 'Сиделка', 'Рыбообработчик', 'Кондитер',
       'Переводчик', 'Программист', 'Кровельщик', 'Зоотехник', 'Токарь',
       'Учитель', 'Монтажник', 'Парикмахер', 'Асфальтобетонщик',
       'Штукатур', 'Швея', 'Диспетчер', 'Проектировщик', 'Дизайнер',
       'Охранник', 'Флорист', 'Экспедитор', 'Электромонтер', 'Электрик',
       'Заведующий', 'Инструктор', 'Контролер', 'Педагог', 'Дворник',
       'Пивовар', 'Супервайзер', 'Аудитор', 'Бригадир', 'Бурильщик',
       'Садовник', 'Стилист', 'Установщик', 'Автоэлектрик', 'Ювелир',
       'Кузнец', 'Фельдшер', 'Фотограф', 'Тренер', 'Изолировщик',
       'Мастер-бровист', 'Отделочник', 'Энергетик', 'Логист', 'Маляр',
       'Врач', 'Плиточник', 'Копирайтер', 'Плотник', 'Слесарь', 'Кинолог',
       'Архитектор', 'Массажист', 'Шиномонтажник', 'Модель', 'Сборщик',
       'Системный администратор', 'Столяр', 'Домработница, домработник',
       'Специалист по химчистке', 'Адвокат', 'Промышленный альпинист',
       'Кассир', 'Библиотекарь', 'Видеооператор', 'Геодезист',
       'Журналист', 'Няня', 'Прораб', 'Бухгалтер', 'Сантехник', 'Сметчик',
       'Автослесарь', 'Визажист', 'Каменщик', 'Мойщик', 'Смотритель',
       'Товаровед', 'Жестянщик', 'Замерщик', 'Скульптор', 'Маркетолог',
       'Обивщик', 'Оклейщик', 'Преподаватель', 'Арматурщик', 'Бетонщик',
       'Гример', 'Гардеробщик', 'Колорист', 'Стяжечник',
       'Мастер татуировки', 'Техник', 'Хореограф', 'Секретарь',
       'Технолог', 'Музыкант', 'Аниматор', 'Консультант', 'Печатник',
       'Специалист по взысканию задолженности / Коллектор', 'Воспитатель',
       'Пекарь', 'Артист', 'Консьерж', 'Сторож', 'Редактор', 'Художник',
       'Упаковщик', 'Экономист', 'Физик', 'Медрегистратор',
       'Гувернантка, гувернер', 'Зооняня, рабочий по уходу за животными',
       'Рыбак', 'Аппаратчик', 'Промоутер', 'Резчик', 'Электромонтажник',
       'Закройщик', 'Дневальный', 'Портной', 'Вальцовщик', 'Санитар',
       'Водолаз', 'Заместитель', 'Комендант', 'Сортировщик', 'Бармен',
       'Аналитик', 'Авторазборщик', 'Пожарный', 'Советник',
       'Транспортерщик', 'Укладчик', 'Электрогазосварщик', 'Буфетчик',
       'Регистратор', 'Кабельщик', 'Рентгенолаборант', 'Интервьюер',
       'Корреспондент', 'Мастер по наращиванию ресниц',
       'Оперуполномоченный', 'Осветитель, светотехник', 'Официант',
       'Провизор', 'Делопроизводитель', 'Наладчик', 'Репетитор',
       'Распространитель', 'Такелажник', 'Эколог',
       'Tорговый представитель', 'Хостес', 'Декларант, таможенный брокер',
       'Акушер', 'Газорезчик', 'Почтальон', 'Мерчендайзер', 'Стивидор',
       'Специалист по изготовлению мебели', 'Кальянщик',
       'Кредитный специалист', 'Следователь', 'Жаровщик', 'Координатор',
       'Куратор', 'Электромеханик', 'Распиловщик', 'Фармацевт',
       'Моторист', 'Дефектолог', 'Лаборант', 'Приемщик', 'Полицейский',
       'Детейлер', 'Боец', 'Военнослужащий по контракту', 'Психолог',
       'Оптик', 'Крупье', 'Организатор', 'Синоптик', 'Сюрвейер', 'Диджей',
       'Мотомеханик', 'Геолог', 'Крепильщик', 'Методист', 'Судоводитель',
       'Озеленитель', 'Гладильщик', 'Дефектоскопист', 'Докер-механизатор',
       'Промывальщик геологических проб', 'Натурщик', 'Обвальщик',
       'Автомаляр', 'Дезинфектор', 'Повар', 'Суперинтендант', 'Тальман',
       'Танцовщица, танцовщик', 'Растениевод', 'Модельер', 'Агроном',
       'Архивариус', 'Банщик', 'Биолог', 'Кондуктор', 'Пилот',
       'Гид, экскурсовод', 'Донкерман', 'Боцман', 'Метеоролог',
       'Оформитель', 'Полировщик', 'Оператор', 'Весовщик', 'Дилер',
       'Дознаватель', 'Документовед', 'Звукорежиссер', 'Тонировщик',
       'Сомелье, кавист', 'Кастелянша, заведующий бельевой', 'Конюх',
       'Косильщик', 'Коптильщик', 'Кузовщик', 'Маркшейдер',
       'Операционист', 'Охотовед', 'Пескоструйщик', 'Прачечник',
       'Пчеловод', 'Животновод', 'Декоратор', 'Вальщик леса, лесоруб',
       'Микробиолог', 'Стрелок', 'Фрезеровщик', 'Чертежник', 'Шлифовщик',
       'Радиотелеграфист', 'Ревизор', 'Шишкарь', 'Сыровар', 'Теплотехник',
       'Учетчик', 'Финансист', 'Чистильщик'], dtype=object)

In [26]:
df[df['по должности-лемме']=='Ревизор'].count()

query                 1
по должности-лемме    1
dtype: int64